---
title: "Research Memo - Dominant Apprehension Imbalance"
author: Andrew K. Sanford
pdf-engine: xelatex
date: 7/29/2026
cache: false
format:
  pdf:
    keep-tex: true
    documentclass: article
    papersize: letter
    mainfont: Arial
    fontsize: 11pt

    nclude-in-header:
      text: |
        \setkomafont{title}{\medium}
        \pagenumbering{gobble}
    geometry:
      - top=0.5in
      - left=1in
      - right=1in
      - bottom=0.75in
---

\thispagestyle{empty}

**Re:** \[Is the distribution of Dominant Apprehension Types balanced?\]

The distribution of dominant apprehension types (either group discussions or solo conversations) is grossly imbalanced across all possible categories (group discussions, solo conversations, and equal apprehension) but becomes roughly balanced when excluding the equal apprehension group.

{{< embed ../../scripts/eda_dependents.qmd#apprehension_grid >}}

This mild imbalance is still very suitable for binary classification.

Roughly \~10% of respondents were equal on both types, however. This would be a very imbalanced and difficult to use sample for 3-way classification. [My recommendation is to pursue **binary classification** for this problem.]{.underline}

Note that this decision requires excluding the 16 ‘Equal’ observations from training and validation sets, as well as rendering them unusable for generating most performance metrics in the test set. Confidence values for predictions on ‘Equal’ observations could still be useful for evaluating model calibration, with a well-calibrated model being expected to make low-confidence predictions for such observations.

*NOTE: The engineering of 'Dominant Transportation Method' occurs in the clean_data.qmd script.*

*NOTE: Rendering of the above figures occurs in the eda_dependents.qmd script.*
