---
title: "Research Memo - Transportation Method Engineering"
author: Andrew K. Sanford
pdf-engine: xelatex
date: 7/30/2026
cache: false
format:
  pdf:
    keep-tex: true
    documentclass: article
    papersize: letter
    mainfont: Arial
    fontsize: 11pt

    nclude-in-header:
      text: |
        \setkomafont{title}{\medium}
        \pagenumbering{gobble}
    geometry:
      - top=0.5in
      - left=1in
      - right=1in
      - bottom=0.75in
---

**Re:** \[How is Dominant Transportation Method determined?\]

Dominant Transportation is an engineered outcome variable that identifies the greatest of two interactive scores (if any): Estimated monthly rideshare usage & estimated monthly public transit usage.

```{r}
#| eval: FALSE
#| echo: TRUE
# Set numeric values for transportation variables
usage_monthly <- c(
  "Never"                     = 0,
  "0-1 days a month"          = 1,
  "2-4 days a month"          = 3,
  "4-8 days a month"          = 6,
  "8 or more days a month"    = 8
  )
usage_daily <- c(
  "1-2 rides in a typical day"       = 1.5,
  "3-4 rides in a typical day"       = 3.5,
  "5-6 rides in a typical day"       = 5.5,
  "7 or more rides in a typical day" = 7
  )

# Calculate highest usage transport method
survey <- survey |>
  mutate(
    
#   Convert 3-month usage variables to numeric
    across(c(q26_public_transit_3months, q28_rideshare_3months), ~ usage_monthly[.x]),
    
#   Convert typical daily usage variables to numeric
    across(c(q27_public_transit_dayuse, q29_rideshare_dayuse), ~ usage_daily[.x]),

#   Multiply usage over past 3 months by typical daily usage (usage count estimate)
    public_transit_count = q26_public_transit_3months * q27_public_transit_dayuse,
    rideshare_count = q28_rideshare_3months * q29_rideshare_dayuse,

#   Assign highest usage transport method (equal if BA)
    highest_transport = case_when(
      public_transit_count > rideshare_count ~ "public_transit",
      rideshare_count > public_transit_count ~ "rideshare",
      public_transit_count == 0 & rideshare_count == 0 ~ "neither",
      .default = "equal" )
    )
```

After numericizing values from a participants' survey responses, relevant questions were sorted into these two groups, depending on which transportation method each question targeted. Each group then had the corresponding values multiplied to estimate the number of monthly trips for both transportation methods. The Dominant Transportation Method was then assigned one of four values.

- If both scores have a value of 0, a participant is assigned to the 'neither' category (indicated no rideshare or public transit use)
- If both scores have a value > 0, but are still equal, a participant is assigned to the 'equal' category (indicated equal usage of both methods)
- If there was a greater value between estimated rideshare usage and estimated public transit usage, a participant was assigned to the category with higher usage.

*NOTE: This code for engineering 'Dominant Transportation Method' occurs in the clean_data.qmd script.*
