---
title: "Research Memo - Dominant Transportation Imbalance"
author: Andrew K. Sanford
pdf-engine: xelatex
date: 7/29/2026
cache: false
format:
  pdf:
    keep-tex: false
    documentclass: article
    papersize: letter
    mainfont: Arial
    fontsize: 11pt

    nclude-in-header:
      text: |
        \setkomafont{title}{\medium}
        \pagenumbering{gobble}
    geometry:
      - top=0.5in
      - left=1in
      - right=1in
      - bottom=0.75in
---

\thispagestyle{empty}

**Re:** \[Is the distribution of Dominant Transportation Methods balanced?\]

The distribution of Dominant Transportation Methods is grossly imbalanced when considering all possible categories (rideshare, public transit, neither, equal), however the distribution becomes roughly balanced when collapsing categories down to public transit vs. all other possibilities combined.

{{< embed ../../scripts/eda_dependents.qmd#transportation_grid >}}

These figures illustrate the dominance of public transit use is far more prevalent than all other categories, even when combined. The right-hand plot is a direct comparison of public transit dominance versus the combined count of rideshare, neither, and equal use respondents.

Attempting to build a 4-way classifier with the current dataset will prove difficult due to the limited sample size for our minority categories, and the challenges of resampling procedures with the inherently complicated natural language data we are using as inputs. When categories are collapsed as seen in the right-hand plot, however, our data immediately becomes much more balanced and thereby preferable for training a classifier. For these reasons, my recommendation [is to pursue a **binary classification** of whether of not a respondent primarily uses public transit.]{.underline}

*NOTE: The engineering of 'Dominant Transportation Method' occurs in the clean_data.qmd script.*

*NOTE: Rendering of the above figures occurs in the eda_dependents.qmd script.*
